name: 'Create ECR Repo if Missing'
description: 'A GitHub Action for creating AWS ECR repositories if they don''t already exist'
inputs:
  DOCKER_REPO_NAME:
    # Ex: 'byuapi-classes-v3-app' would allow you to tag and push images to
    # $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/byuapi-classes-v3-app:some-tag
    description: 'The ECR repository name'
    required: true
  NUM_DAYS_BEFORE_EXPIRING_UNTAGGED_IMAGES:
    description: 'The number of days after which untagged images will expire'
    required: false
    default: '30'

  # These next two go together to create the "Expire old images as new ones are built" lifecycle policy
  TAG_PREFIX:
    description: 'The image tag prefix used so that we can expire old images as new ones are built'
    required: false
  NUM_TAGGED_IMAGES_TO_RETAIN:
    description: 'The number of images with the given prefix to retain'
    required: false
    # Defaults to retaining all tagged images
runs:
  using: 'node18'
  main: 'dist/index.js'
