name: "Test"
on:
  push:
    branches:
      - main
env:
  aws_account: "977306314792"
  aws_gha_role: create-ecr-repo-if-missing-dev-gha

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::${{ env.aws_account }}:role/${{ env.aws_gha_role }}"
          role-session-name: ${{ github.sha }}
          aws-region: us-west-2
      - name: Log into Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Create ECR repo if missing
        uses: ./
        with:
          DOCKER_REPO_NAME: test-repo
  test-fancy-case:
    name: Test the Fancy Case
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::${{ env.aws_account }}:role/${{ env.aws_gha_role }}"
          role-session-name: ${{ github.sha }}
          aws-region: us-west-2
      - name: Log into Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Create ECR repo if missing
        uses: ./
        with:
          DOCKER_REPO_NAME: test-repo-fancy
          NUM_DAYS_BEFORE_EXPIRING_UNTAGGED_IMAGES: 14
          TAG_PREFIX: 'dev-v'
          NUM_TAGGED_IMAGES_TO_RETAIN: 5
